version: '3'

services:

  cog-services:
    restart: always
    build:
      context: ./services
    entrypoint:
    - /bin/ash
    - -eu
    - -c
    - |
      echo "waiting"
      /wait-for -it contracts:8545 -t 300
      echo "starting"
      exec /ds-node
    environment:
      PORT: "8181"
      CHAIN_ID: "1337"
      SEQUENCER_PRIVATE_KEY: "095a37ef5b5d87db7fe50551725cb64804c8c554868d3d729c0dd17f0e664c87"
      SEQUENCER_PROVIDER_URL_HTTP: "http://contracts:8545"
      SEQUENCER_PROVIDER_URL_WS: "ws://contracts:8545"
      INDEXER_WATCH_PENDING: "false"
      INDEXER_PROVIDER_URL_HTTP: "http://contracts:8545"
      INDEXER_PROVIDER_URL_WS: "ws://contracts:8545"
    ports:
      - 3080:8080
    depends_on:
      - contracts

  # run the integration tests in docker
  #
  #   > docker-compose --profile=test up --exit-code-from cog-tests --build
  #
  contracts:
    profiles: ["test"]
    restart: always
    platform: linux/amd64
    build:
      context: ./examples/cornseekers/contracts
    ports:
      - 3045:8545
  cog-tests:
    profiles: ["test"]
    build:
      context: ./services
    entrypoint:
    - /bin/ash
    - -eu
    - -c
    - |
      echo "waiting for services"
      /wait-for -it cog-services:8080 -t 300
      sleep 10
      echo "testing"
      exec /integration.test -test.v -test.count=1
    environment:
      QUERY_ENDPOINT: "http://cog-services:8080/query"
    depends_on:
      - cog-services

